name: CI

on:
  push:
    branches: [ master ] 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100  # select a 'sdk'.'version' from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json
    - name: build
      run: dotnet build JBSnorro/JBSnorro.csproj
    - name: Create ssh access file
      run: mkdir ~/.ssh && echo "{{ secrets.PLAYGROUND_SSH_KEY }}" > ~/.ssh/playground
    - name: test
      run: dotnet test JBSnorro.Tests/JBSnorro.Tests.csproj --runtime net6
      timeout-minutes: 5
      env:
        SSH_FILE: "~/.ssh/playground"
