name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

env:
    DOTNET_VERSION: 7.0.102  # select a 'sdk'.'version' from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/7.0/releases.json
    DOTNET_CLI_TELEMETRY_OPTOUT: true

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
          
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet build JBSnorro/JBSnorro.csproj

    - name: Create SSH_FILE env var 
      run: echo "SSH_FILE=$HOME/.ssh/playground" >> $GITHUB_ENV

    - name: Create NODE_PATH env var
      run: echo "NODE_PATH=$(which node)$([[ '${{ matrix.os }}' == 'windows-latest' ]] && echo -n '.exe')" >> $GITHUB_ENV 

    - name: Create ssh access file
      run: |
          mkdir "$(dirname "$SSH_FILE")"
          echo "${{secrets.PLAYGROUND_SSH_KEY}}" > "$SSH_FILE"
          
          # Give access to ssh key (Linux)
          if [[ '${{ matrix.os }}' == 'ubuntu-latest' ]]; then
              sudo chmod 600 "$SSH_FILE"
          fi

    - name: Append GitHub ssh host
      run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Test
      run: | 
          dotnet test JBSnorro.Tests/JBSnorro.Tests.csproj
          # Can't add '--no-build' as optimization because the test project hasn't been built yet
      timeout-minutes: 5
