name: CI

on:
  push:
    branches: [ master ] 
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win10-x64
          - os: ubuntu-latest
            runtime: linux-x64
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101  # select a 'sdk'.'version' from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json
    - name: build
      run: dotnet build JBSnorro/JBSnorro.csproj
    - name: Create ssh access file
      shell: bash
      run: |
        mkdir ~/.ssh
        echo "${{secrets.PLAYGROUND_SSH_KEY}}" > ~/.ssh/playground
        sudo chmod 600 ~/.ssh/playground
    - name: test
      run: | 
          export SSH_FILE="$HOME/.ssh/playground"
          dotnet test JBSnorro.Tests/JBSnorro.Tests.csproj --runtime ${{ matrix.runtime }} --framework net6.0
      timeout-minutes: 5
