name: Publish

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    paths:
      - ".github/workflows.Publish.yml"

jobs:
  publish:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Detect if version changed
        run: |
          current_version=$(bash .github/get_current_version.sh | xargs)
          published_version=$(bash .github/get_published_version.sh | xargs)
          echo "current_version: \"$current_version\""
          echo "published_version: \"$published_version\""

          is_up_to_date=$([[ "$current_version" == "$published_version" ]] && echo true || echo false)
          echo "is_up_to_date: $is_up_to_date"

          if [[ "$(is_up_to_date)" == "true" ]]; then
              echo "Up-to-date"
          else
              echo "PUBLISH=true" >> $GITHUB_ENV
              echo "Publishing"
          fi

      - name: Setup .NET Core
        if: ${{ env.PUBLISH == 'true' }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        if: ${{ env.PUBLISH == 'true' }}
        run: dotnet restore

      - name: Build
        if: ${{ env.PUBLISH == 'true' }}
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        if: ${{ env.PUBLISH == 'true' && github.ref == 'refs/heads/main' }}
        uses: alirezanet/publish-nuget@v3.0.0 # atm, this bugfix is not merged yet: https://github.com/brandedoutcast/publish-nuget/pull/62
        with:
          PROJECT_FILE_PATH: JBSnorro/JBSnorro.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true
