name: Publish

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    paths:
      - ".github/workflows/Publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Detect if version changed
        run: |
          current_version=$(bash .github/get_current_version.sh | xargs)
          published_version=$(bash .github/get_published_version.sh | xargs)
          echo "current_version: \"$current_version\""
          echo "published_version: \"$published_version\""

          is_up_to_date=$([[ "$current_version" == "$published_version" ]] && echo true || echo false)

          if [[ "${is_up_to_date}" == "true" ]]; then
              echo "Up-to-date"
          else
              echo "PUBLISH=true" >> $GITHUB_ENV
              echo "Publishing"
          fi

      - name: Setup .NET Core
        if: ${{ env.PUBLISH == 'true' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        if: ${{ env.PUBLISH == 'true' }}
        run: dotnet restore

      - name: Build
        if: ${{ env.PUBLISH == 'true' }}
        run: dotnet build --configuration Release --no-restore

      - name: Wait for ubuntu CI
        uses: fountainhead/action-wait-for-check@v1.1.0
        if: ${{ env.PUBLISH == 'true' }}
        id: wait-for-test-ubuntu
        with:
          checkName: test (ubuntu-latest)
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail if ubuntu CI failed
        if: ${{ env.PUBLISH == 'true' && steps.wait-for-test-ubuntu.outputs.conclusion != 'success' }}
        run: echo "Conclusion=${{ steps.wait-for-ubuntu-test.outputs.conclusion }}" && exit 1

      - name: Wait for windows CI
        uses: fountainhead/action-wait-for-check@v1.1.0
        if: ${{ env.PUBLISH == 'true' }}
        id: wait-for-test-windows
        with:
          checkName: test (windows-latest)
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail if windows CI failed
        if: ${{ env.PUBLISH == 'true' && steps.wait-for-test-windows.outputs.conclusion != 'success' }}
        run: echo "Conclusion=${{ steps.wait-for-windows-test.outputs.conclusion }}" && exit 1

      - name: Publish
        if: ${{ env.PUBLISH == 'true' && github.ref == 'refs/heads/main' }}
        uses: alirezanet/publish-nuget@v3.0.4 # atm, this bugfix is not merged yet: https://github.com/brandedoutcast/publish-nuget/pull/62
        with:
          PROJECT_FILE_PATH: JBSnorro/JBSnorro.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true
